// GENERATED by scratch/gen_catalogue_v2.py from docs/data/catalogue-v2.json. Do not edit by hand.
// Layer shares inside a layer are percentages (sum 100). See docs/catalogue-v2.md.

export interface ItemRow { id: string; label: string; material: string; share: number; variants: number }
export interface NaturalRow extends ItemRow { group: "flora" | "fauna"; resist: number }

export const LAYER_SHARE = {"A": 0.7, "B": 0.1, "C": 0.2} as const;
export const NATURAL_CAL = {"tauFlora": 72.13, "tauFauna": 27.91, "passesPerCrossing": 10, "passesPerDeposit": 5} as const;

export const ITEMS_A: ItemRow[] = [
 {
  "id": "frag_small",
  "label": "plastic pieces 0–2.5 cm",
  "material": "plastic_fragment",
  "share": 13.8616,
  "variants": 4
 },
 {
  "id": "frag_mid",
  "label": "plastic pieces 2.5–50 cm",
  "material": "plastic_fragment",
  "share": 15.0861,
  "variants": 4
 },
 {
  "id": "frag_large",
  "label": "plastic pieces > 50 cm",
  "material": "plastic_fragment",
  "share": 1.1707,
  "variants": 3
 },
 {
  "id": "foam_pieces",
  "label": "foam / polystyrene pieces and packaging",
  "material": "plastic_foam",
  "share": 0.2941,
  "variants": 2
 },
 {
  "id": "foam_sponge",
  "label": "foam sponge",
  "material": "plastic_foam",
  "share": 1.171,
  "variants": 3
 },
 {
  "id": "plastic_other",
  "label": "other identifiable plastic item",
  "material": "plastic_rigid",
  "share": 2.8575,
  "variants": 3
 },
 {
  "id": "string",
  "label": "string and cord (< 1 cm)",
  "material": "plastic_cordage",
  "share": 13.783,
  "variants": 4
 },
 {
  "id": "rope",
  "label": "rope (> 1 cm)",
  "material": "plastic_cordage",
  "share": 0.9701,
  "variants": 2
 },
 {
  "id": "net_pieces",
  "label": "nets, net pieces, tangled nets",
  "material": "plastic_cordage",
  "share": 2.4324,
  "variants": 3
 },
 {
  "id": "fishing_line",
  "label": "fishing line / monofilament",
  "material": "plastic_cordage",
  "share": 0.3998,
  "variants": 2
 },
 {
  "id": "strapping",
  "label": "strapping bands",
  "material": "plastic_cordage",
  "share": 0.6308,
  "variants": 2
 },
 {
  "id": "cable_tie",
  "label": "cable ties",
  "material": "plastic_rigid",
  "share": 0.0073,
  "variants": 1
 },
 {
  "id": "six_pack",
  "label": "six-pack rings / yokes",
  "material": "plastic_film",
  "share": 0.1144,
  "variants": 1
 },
 {
  "id": "cap_plastic",
  "label": "plastic caps, lids, rings",
  "material": "plastic_rigid",
  "share": 5.2778,
  "variants": 4
 },
 {
  "id": "cap_metal",
  "label": "metal bottle caps, lids, pull tabs",
  "material": "metal_can",
  "share": 0.5584,
  "variants": 2
 },
 {
  "id": "cotton_bud",
  "label": "cotton bud sticks (incl. sanitary mix)",
  "material": "plastic_rigid",
  "share": 3.8392,
  "variants": 3
 },
 {
  "id": "cutlery",
  "label": "cutlery, trays",
  "material": "plastic_rigid",
  "share": 1.1842,
  "variants": 3
 },
 {
  "id": "straw",
  "label": "straws, stirrers",
  "material": "plastic_rigid",
  "share": 0.1595,
  "variants": 1
 },
 {
  "id": "lighter",
  "label": "cigarette lighters",
  "material": "plastic_rigid",
  "share": 0.224,
  "variants": 2
 },
 {
  "id": "pen",
  "label": "pens and pen lids",
  "material": "plastic_rigid",
  "share": 0.1809,
  "variants": 1
 },
 {
  "id": "comb_glasses",
  "label": "combs, hair brushes, sunglasses",
  "material": "plastic_rigid",
  "share": 0.0454,
  "variants": 1
 },
 {
  "id": "toy",
  "label": "toys, party poppers",
  "material": "plastic_rigid",
  "share": 0.3477,
  "variants": 2
 },
 {
  "id": "cup",
  "label": "cups and cup lids",
  "material": "plastic_rigid",
  "share": 0.5827,
  "variants": 2
 },
 {
  "id": "food_box",
  "label": "food containers incl. fast food",
  "material": "plastic_rigid",
  "share": 0.7999,
  "variants": 2
 },
 {
  "id": "shotgun",
  "label": "shotgun cartridges",
  "material": "plastic_rigid",
  "share": 0.6376,
  "variants": 2
 },
 {
  "id": "light_stick",
  "label": "light sticks (tubes with fluid)",
  "material": "plastic_rigid",
  "share": 0.129,
  "variants": 1
 },
 {
  "id": "tobacco_pack",
  "label": "tobacco pouches / plastic cigarette packaging",
  "material": "plastic_film",
  "share": 0.0456,
  "variants": 1
 },
 {
  "id": "syringe",
  "label": "syringes, needles",
  "material": "plastic_rigid",
  "share": 0.0451,
  "variants": 1
 },
 {
  "id": "med_container",
  "label": "medical / pharmaceutical containers, tubes",
  "material": "plastic_rigid",
  "share": 0.1395,
  "variants": 1
 },
 {
  "id": "bottle_drink",
  "label": "plastic beverage bottles",
  "material": "plastic_rigid",
  "share": 1.8359,
  "variants": 3
 },
 {
  "id": "bottle_clean",
  "label": "cleaner bottles and containers",
  "material": "plastic_rigid",
  "share": 0.3235,
  "variants": 2
 },
 {
  "id": "bottle_cosm",
  "label": "cosmetic / sunscreen bottles",
  "material": "plastic_rigid",
  "share": 0.1741,
  "variants": 1
 },
 {
  "id": "bottle_other",
  "label": "other bottles, oil bottles, jerry cans, injection-gun tubes",
  "material": "plastic_rigid",
  "share": 0.3274,
  "variants": 2
 },
 {
  "id": "bucket",
  "label": "buckets",
  "material": "plastic_rigid",
  "share": 0.0504,
  "variants": 1
 },
 {
  "id": "crate",
  "label": "plastic crates, baskets",
  "material": "plastic_rigid",
  "share": 0.0561,
  "variants": 1
 },
 {
  "id": "bag",
  "label": "plastic bags",
  "material": "plastic_film",
  "share": 1.746,
  "variants": 3
 },
 {
  "id": "wrapper",
  "label": "crisp packets, sweet wrappers",
  "material": "plastic_film",
  "share": 3.0598,
  "variants": 3
 },
 {
  "id": "lolly_stick",
  "label": "lolly sticks",
  "material": "plastic_rigid",
  "share": 0.0575,
  "variants": 1
 },
 {
  "id": "sheet",
  "label": "sheets, industrial packaging, sheeting",
  "material": "plastic_film",
  "share": 0.4395,
  "variants": 2
 },
 {
  "id": "mesh_bag",
  "label": "mesh vegetable bags",
  "material": "plastic_film",
  "share": 0.1288,
  "variants": 1
 },
 {
  "id": "feed_bag",
  "label": "fertiliser / animal-feed bags",
  "material": "plastic_film",
  "share": 0.0223,
  "variants": 1
 },
 {
  "id": "dog_bag",
  "label": "dog-faeces bags",
  "material": "plastic_film",
  "share": 0.0502,
  "variants": 1
 },
 {
  "id": "tape",
  "label": "masking tape",
  "material": "plastic_film",
  "share": 0.0149,
  "variants": 1
 },
 {
  "id": "glove",
  "label": "gloves",
  "material": "plastic_film",
  "share": 0.1662,
  "variants": 1
 },
 {
  "id": "towel",
  "label": "sanitary towels, liners",
  "material": "composite_misc",
  "share": 0.8106,
  "variants": 2
 },
 {
  "id": "tampon",
  "label": "tampons and applicators",
  "material": "textile",
  "share": 0.2223,
  "variants": 2
 },
 {
  "id": "diaper",
  "label": "diapers, nappies",
  "material": "composite_misc",
  "share": 0.0059,
  "variants": 1
 },
 {
  "id": "hygiene_misc",
  "label": "other hygiene (tissue, razors)",
  "material": "composite_misc",
  "share": 1.4305,
  "variants": 3
 },
 {
  "id": "fresheners",
  "label": "toilet fresheners",
  "material": "plastic_rigid",
  "share": 0.0282,
  "variants": 1
 },
 {
  "id": "medical_other",
  "label": "other medical items (swabs, plasters)",
  "material": "composite_misc",
  "share": 1.6457,
  "variants": 3
 },
 {
  "id": "shoe_plastic",
  "label": "plastic shoes, sandals, flip-flops",
  "material": "plastic_rigid",
  "share": 0.1792,
  "variants": 1
 },
 {
  "id": "helmet",
  "label": "hard hats",
  "material": "plastic_rigid",
  "share": 0.02,
  "variants": 1
 },
 {
  "id": "float_buoy",
  "label": "floats, buoys",
  "material": "plastic_rigid",
  "share": 0.1465,
  "variants": 1
 },
 {
  "id": "fishing_gear",
  "label": "plastic fishing gear (pots, tags, trays, holders)",
  "material": "plastic_rigid",
  "share": 0.1533,
  "variants": 1
 },
 {
  "id": "car_part",
  "label": "car parts",
  "material": "plastic_rigid",
  "share": 0.038,
  "variants": 1
 },
 {
  "id": "fibreglass",
  "label": "fibreglass fragments",
  "material": "plastic_fragment",
  "share": 0.0318,
  "variants": 1
 },
 {
  "id": "cone",
  "label": "traffic cones",
  "material": "plastic_rigid",
  "share": 0.0011,
  "variants": 1
 },
 {
  "id": "flower_pot",
  "label": "plastic flower pots",
  "material": "plastic_rigid",
  "share": 0.0208,
  "variants": 1
 },
 {
  "id": "plastic_constr",
  "label": "plastic construction waste",
  "material": "plastic_rigid",
  "share": 0.0147,
  "variants": 1
 },
 {
  "id": "acetate_butt",
  "label": "cigarette butts and filters",
  "material": "acetate_filter",
  "share": 6.1574,
  "variants": 4
 },
 {
  "id": "wax",
  "label": "paraffin / wax",
  "material": "wax",
  "share": 2.9466,
  "variants": 3
 },
 {
  "id": "balloon",
  "label": "balloons and balloon sticks",
  "material": "rubber",
  "share": 0.7624,
  "variants": 2
 },
 {
  "id": "ball",
  "label": "balls",
  "material": "rubber",
  "share": 0.0014,
  "variants": 1
 },
 {
  "id": "rubber_piece",
  "label": "rubber pieces, inner tubes, wheels",
  "material": "rubber",
  "share": 0.6801,
  "variants": 2
 },
 {
  "id": "tyre",
  "label": "tyres and belts",
  "material": "rubber",
  "share": 0.073,
  "variants": 1
 },
 {
  "id": "rubber_boot",
  "label": "rubber boots",
  "material": "rubber",
  "share": 0.0175,
  "variants": 1
 },
 {
  "id": "condom",
  "label": "condoms",
  "material": "rubber",
  "share": 0.1352,
  "variants": 1
 },
 {
  "id": "rubber_band",
  "label": "rubber bands",
  "material": "rubber",
  "share": 0.0265,
  "variants": 1
 },
 {
  "id": "paper_misc",
  "label": "other paper items, paper fragments",
  "material": "paper",
  "share": 0.7041,
  "variants": 2
 },
 {
  "id": "cig_pack",
  "label": "cigarette packets",
  "material": "paper",
  "share": 0.5489,
  "variants": 2
 },
 {
  "id": "paper_cup",
  "label": "paper cups, trays, wrappers, packaging",
  "material": "paper",
  "share": 0.2753,
  "variants": 2
 },
 {
  "id": "carton",
  "label": "cartons / tetrapack",
  "material": "paper",
  "share": 0.1631,
  "variants": 1
 },
 {
  "id": "cardboard",
  "label": "cardboard boxes and fragments",
  "material": "paper",
  "share": 0.1569,
  "variants": 1
 },
 {
  "id": "newspaper",
  "label": "newspapers, magazines, firework tubes",
  "material": "paper",
  "share": 0.295,
  "variants": 2
 },
 {
  "id": "paper_bag",
  "label": "paper bags",
  "material": "paper",
  "share": 0.0502,
  "variants": 1
 },
 {
  "id": "wood_piece",
  "label": "worked wood pieces",
  "material": "wood_worked",
  "share": 0.9213,
  "variants": 2
 },
 {
  "id": "wood_stick",
  "label": "ice-cream sticks, chopsticks, toothpicks",
  "material": "wood_worked",
  "share": 0.2395,
  "variants": 2
 },
 {
  "id": "cork",
  "label": "corks",
  "material": "wood_worked",
  "share": 0.098,
  "variants": 1
 },
 {
  "id": "pallet",
  "label": "pallets, crates, boards, timber",
  "material": "wood_worked",
  "share": 0.1454,
  "variants": 1
 },
 {
  "id": "brush",
  "label": "paint brushes",
  "material": "wood_worked",
  "share": 0.0659,
  "variants": 1
 },
 {
  "id": "match",
  "label": "matches, fireworks",
  "material": "wood_worked",
  "share": 0.0206,
  "variants": 1
 },
 {
  "id": "clothing",
  "label": "clothing, rags, hats, towels",
  "material": "textile",
  "share": 0.6632,
  "variants": 2
 },
 {
  "id": "shoe_textile",
  "label": "shoes and sandals (leather, cloth)",
  "material": "textile",
  "share": 0.0775,
  "variants": 1
 },
 {
  "id": "carpet",
  "label": "carpet, furnishing",
  "material": "textile",
  "share": 0.0654,
  "variants": 1
 },
 {
  "id": "sacking",
  "label": "sacking, canvas, sails",
  "material": "textile",
  "share": 0.0603,
  "variants": 1
 },
 {
  "id": "textile_bag",
  "label": "backpacks and bags",
  "material": "textile",
  "share": 0.0025,
  "variants": 1
 },
 {
  "id": "textile_rope",
  "label": "textile rope, string, nets",
  "material": "textile",
  "share": 0.0685,
  "variants": 1
 },
 {
  "id": "glass_bottle",
  "label": "glass / ceramic bottles incl. pieces",
  "material": "glass",
  "share": 1.0901,
  "variants": 3
 },
 {
  "id": "glass_jar",
  "label": "jars incl. pieces",
  "material": "glass",
  "share": 0.0166,
  "variants": 1
 },
 {
  "id": "glass_frag",
  "label": "glass or ceramic fragments",
  "material": "glass",
  "share": 0.2012,
  "variants": 2
 },
 {
  "id": "glass_other",
  "label": "other glass items, large glass objects",
  "material": "glass",
  "share": 0.4821,
  "variants": 2
 },
 {
  "id": "tableware",
  "label": "tableware (plates, cups)",
  "material": "glass",
  "share": 0.0014,
  "variants": 1
 },
 {
  "id": "glass_buoy",
  "label": "glass buoys, octopus pots",
  "material": "glass",
  "share": 0.0011,
  "variants": 1
 },
 {
  "id": "construction",
  "label": "construction material (brick, cement, pipes)",
  "material": "ceramic_construction",
  "share": 0.4581,
  "variants": 2
 },
 {
  "id": "can_drink",
  "label": "beverage cans",
  "material": "metal_can",
  "share": 0.6686,
  "variants": 2
 },
 {
  "id": "can_food",
  "label": "food cans, pint tins, other cans",
  "material": "metal_can",
  "share": 0.0702,
  "variants": 1
 },
 {
  "id": "foil",
  "label": "foil wrappers, aluminium foil",
  "material": "metal_foil",
  "share": 0.3984,
  "variants": 2
 },
 {
  "id": "aerosol",
  "label": "aerosol / spray cans",
  "material": "metal_can",
  "share": 0.104,
  "variants": 1
 },
 {
  "id": "drum",
  "label": "gas bottles, drums, containers",
  "material": "metal_can",
  "share": 0.0989,
  "variants": 1
 },
 {
  "id": "wire",
  "label": "wire, mesh, barbed wire",
  "material": "metal_foil",
  "share": 0.1431,
  "variants": 1
 },
 {
  "id": "metal_piece",
  "label": "other metal pieces, scrap",
  "material": "metal_foil",
  "share": 0.2857,
  "variants": 2
 },
 {
  "id": "fishing_metal",
  "label": "metal fishing gear (sinkers, hooks, pots)",
  "material": "metal_foil",
  "share": 0.0197,
  "variants": 1
 },
 {
  "id": "bbq",
  "label": "disposable BBQs",
  "material": "metal_foil",
  "share": 0.013,
  "variants": 1
 },
 {
  "id": "metal_table",
  "label": "metal tableware",
  "material": "metal_foil",
  "share": 0.0042,
  "variants": 1
 },
 {
  "id": "battery",
  "label": "household batteries",
  "material": "battery",
  "share": 0.3266,
  "variants": 2
 },
 {
  "id": "misc_other",
  "label": "other / unidentified",
  "material": "composite_misc",
  "share": 0.0189,
  "variants": 1
 }
];

export const ITEMS_B: ItemRow[] = [
 {
  "id": "smartphone",
  "label": "smartphone",
  "material": "ewaste_device",
  "share": 7.843,
  "variants": 3
 },
 {
  "id": "feature_phone",
  "label": "feature phone",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "earbuds",
  "label": "earphones / earbuds",
  "material": "ewaste_device",
  "share": 6.863,
  "variants": 3
 },
 {
  "id": "headphones",
  "label": "headphones",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "charger",
  "label": "phone charger / adapter",
  "material": "ewaste_device",
  "share": 5.882,
  "variants": 3
 },
 {
  "id": "usb_cable",
  "label": "USB / charging cable",
  "material": "plastic_cordage",
  "share": 8.824,
  "variants": 3
 },
 {
  "id": "usb_stick",
  "label": "USB stick, memory card",
  "material": "ewaste_board",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "hdd",
  "label": "hard-disk drive",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "router",
  "label": "router / modem",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "pcb",
  "label": "bare circuit board",
  "material": "ewaste_board",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "laptop",
  "label": "laptop / tablet",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "screen",
  "label": "broken screen, monitor, TV",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "led_bulb",
  "label": "LED bulb",
  "material": "ewaste_device",
  "share": 3.922,
  "variants": 2
 },
 {
  "id": "tube_lamp",
  "label": "fluorescent tube",
  "material": "glass",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "bulb",
  "label": "incandescent bulb",
  "material": "glass",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "remote",
  "label": "remote control",
  "material": "ewaste_device",
  "share": 4.902,
  "variants": 2
 },
 {
  "id": "vape",
  "label": "disposable e-cigarette",
  "material": "ewaste_device",
  "share": 6.863,
  "variants": 3
 },
 {
  "id": "powerbank",
  "label": "power bank",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "toothbrush",
  "label": "electric toothbrush",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "shaver",
  "label": "shaver, hair dryer",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "calculator",
  "label": "calculator",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "controller",
  "label": "game controller",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "keyboard",
  "label": "keyboard, mouse",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "camera",
  "label": "camera",
  "material": "ewaste_device",
  "share": 0.98,
  "variants": 1
 },
 {
  "id": "toy_elec",
  "label": "electronic toy",
  "material": "ewaste_device",
  "share": 2.941,
  "variants": 2
 },
 {
  "id": "detector",
  "label": "smoke detector",
  "material": "ewaste_device",
  "share": 0.98,
  "variants": 1
 },
 {
  "id": "kitchen_elec",
  "label": "kettle, toaster",
  "material": "ewaste_device",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "battery_aa",
  "label": "AA / AAA battery",
  "material": "battery",
  "share": 3.922,
  "variants": 2
 },
 {
  "id": "battery_coin",
  "label": "coin cell",
  "material": "battery",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "battery_li",
  "label": "lithium battery pack",
  "material": "battery",
  "share": 1.961,
  "variants": 1
 },
 {
  "id": "appliance",
  "label": "appliance fragment (drum, panel)",
  "material": "metal_foil",
  "share": 0.98,
  "variants": 1
 },
 {
  "id": "compressor",
  "label": "fridge / compressor part",
  "material": "metal_foil",
  "share": 0.98,
  "variants": 1
 }
];

export const ITEMS_C: ItemRow[] = [
 {
  "id": "food_waste",
  "label": "food waste",
  "material": "soft_organic",
  "share": 21.739,
  "variants": 3
 },
 {
  "id": "fruit_scrap",
  "label": "fruit peel, bread, kitchen scrap",
  "material": "soft_organic",
  "share": 13.043,
  "variants": 3
 },
 {
  "id": "faeces",
  "label": "faeces",
  "material": "soft_organic",
  "share": 6.522,
  "variants": 3
 },
 {
  "id": "snus",
  "label": "snuff / snus",
  "material": "soft_organic",
  "share": 4.348,
  "variants": 2
 },
 {
  "id": "chicken_bone",
  "label": "chicken bone (broiler)",
  "material": "bone",
  "share": 15.217,
  "variants": 3
 },
 {
  "id": "livestock_bone",
  "label": "beef / pork bone",
  "material": "bone",
  "share": 8.696,
  "variants": 3
 },
 {
  "id": "fish_bone",
  "label": "fish bone",
  "material": "bone",
  "share": 6.522,
  "variants": 3
 },
 {
  "id": "eggshell",
  "label": "eggshell",
  "material": "shell",
  "share": 8.696,
  "variants": 3
 },
 {
  "id": "shellfish",
  "label": "oyster / mussel shell (eaten)",
  "material": "shell",
  "share": 8.696,
  "variants": 3
 },
 {
  "id": "charcoal",
  "label": "charcoal / coal lump",
  "material": "charcoal",
  "share": 6.522,
  "variants": 3
 }
];

export const ITEMS_N: NaturalRow[] = [
 {
  "id": "leaf",
  "label": "leaf",
  "material": "soft_organic",
  "share": 25.0,
  "variants": 3,
  "group": "flora",
  "resist": 0.8
 },
 {
  "id": "petal",
  "label": "petal / flower",
  "material": "soft_organic",
  "share": 6.818,
  "variants": 2,
  "group": "flora",
  "resist": 0.4
 },
 {
  "id": "mushroom",
  "label": "mushroom",
  "material": "soft_organic",
  "share": 2.273,
  "variants": 1,
  "group": "flora",
  "resist": 0.4
 },
 {
  "id": "seed",
  "label": "seed, nut",
  "material": "soft_organic",
  "share": 6.818,
  "variants": 2,
  "group": "flora",
  "resist": 1.5
 },
 {
  "id": "grass",
  "label": "grass, straw",
  "material": "soft_organic",
  "share": 13.636,
  "variants": 2,
  "group": "flora",
  "resist": 3.0
 },
 {
  "id": "twig",
  "label": "twig, branch",
  "material": "wood_natural",
  "share": 11.364,
  "variants": 3,
  "group": "flora",
  "resist": 1.5
 },
 {
  "id": "bark",
  "label": "bark, pine cone",
  "material": "wood_natural",
  "share": 4.545,
  "variants": 2,
  "group": "flora",
  "resist": 2.0
 },
 {
  "id": "insect",
  "label": "insect (beetle)",
  "material": "soft_organic",
  "share": 5.682,
  "variants": 2,
  "group": "fauna",
  "resist": 0.5
 },
 {
  "id": "small_fish",
  "label": "dead small fish",
  "material": "soft_organic",
  "share": 1.136,
  "variants": 1,
  "group": "fauna",
  "resist": 0.5
 },
 {
  "id": "feather",
  "label": "feather",
  "material": "feather_hair",
  "share": 7.955,
  "variants": 3,
  "group": "fauna",
  "resist": 0.7
 },
 {
  "id": "fur",
  "label": "fur tuft",
  "material": "feather_hair",
  "share": 2.273,
  "variants": 1,
  "group": "fauna",
  "resist": 0.7
 },
 {
  "id": "bird_bone",
  "label": "bird bone",
  "material": "bone",
  "share": 1.136,
  "variants": 1,
  "group": "fauna",
  "resist": 1.5
 },
 {
  "id": "wild_bone",
  "label": "wild mammal bone",
  "material": "bone",
  "share": 2.273,
  "variants": 1,
  "group": "fauna",
  "resist": 1.5
 },
 {
  "id": "tooth",
  "label": "tooth",
  "material": "tooth",
  "share": 1.136,
  "variants": 1,
  "group": "fauna",
  "resist": 2.0
 },
 {
  "id": "snail",
  "label": "snail shell",
  "material": "shell",
  "share": 3.409,
  "variants": 2,
  "group": "fauna",
  "resist": 1.5
 },
 {
  "id": "crab",
  "label": "crab / crustacean shell",
  "material": "shell",
  "share": 2.273,
  "variants": 1,
  "group": "fauna",
  "resist": 1.5
 },
 {
  "id": "urchin",
  "label": "sea urchin, starfish",
  "material": "shell",
  "share": 1.136,
  "variants": 1,
  "group": "fauna",
  "resist": 1.5
 },
 {
  "id": "coral",
  "label": "coral fragment",
  "material": "shell",
  "share": 1.136,
  "variants": 1,
  "group": "fauna",
  "resist": 2.0
 }
];
