/**
 * ground/atlas.ts: lookup of sprite atlas cells per catalogue item.
 * The data file is generated by tools/sprites/build_atlas.py.
 *
 * Items that have no sprite of their own borrow one from another item of the same material
 * (stable per item and variant), so the ground never shows flat placeholder squares while
 * the atlas is still being filled. `-1` is returned only if the whole material has no sprite.
 */

import { ITEMS, NATURALS, hash01 } from "@/lib/stratum";
import { SPRITE_CELLS, SPRITE_CELL, ATLAS_COLS, ATLAS_ROWS } from "@/lib/stratum/sprites.data";

export { SPRITE_CELL, ATLAS_COLS, ATLAS_ROWS };
export const ATLAS_URL = "/sprites/atlas.png";

let byMaterial: Map<string, number[]> | null = null;
let materialOf: Map<string, string> | null = null;

function build() {
  byMaterial = new Map();
  materialOf = new Map();
  const add = (id: string, material: string) => {
    materialOf!.set(id, material);
    const cells = SPRITE_CELLS[id];
    if (!cells) return;
    const list = byMaterial!.get(material) ?? [];
    for (const c of cells) if (!list.includes(c)) list.push(c);
    byMaterial!.set(material, list);
  };
  for (const it of ITEMS) add(it.id, it.material);
  for (const n of NATURALS) add(n.id, n.material);
}

/** Atlas cell for an item and its variant, or -1 (flat square) when nothing fits. */
export function spriteCell(itemId: string, variant = 0): number {
  const own = SPRITE_CELLS[itemId];
  if (own && own.length > 0) return own[variant % own.length];
  if (!byMaterial) build();
  const material = materialOf!.get(itemId);
  const pool = material ? byMaterial!.get(material) : undefined;
  if (!pool || pool.length === 0) return -1;
  return pool[Math.floor(hash01(`${itemId}:${variant}`, "sprite") * pool.length)];
}

/** Variant for things that have no record of their own (natural stock): stable per position. */
export function variantAt(itemId: string, x: number, z: number): number {
  return Math.floor(hash01(`${itemId}:${x.toFixed(2)}:${z.toFixed(2)}`, "v") * 1000);
}
