// GENERATED by tools/fragments/build_fragments.py - do not edit.
export interface FragmentInfo {
  id: string;
  /** Pixel size of the cut-out PNG (aspect = w / h). */
  w: number;
  h: number;
}

export const SIDE_FRAGMENTS: FragmentInfo[] = [
  {
    "id": "frag_beams",
    "w": 640,
    "h": 520
  },
  {
    "id": "frag_cantilever",
    "w": 460,
    "h": 640
  },
  {
    "id": "frag_corrugated",
    "w": 331,
    "h": 640
  },
  {
    "id": "frag_fins",
    "w": 263,
    "h": 640
  },
  {
    "id": "frag_glass",
    "w": 498,
    "h": 640
  },
  {
    "id": "frag_pilotis",
    "w": 640,
    "h": 500
  },
  {
    "id": "frag_plates",
    "w": 482,
    "h": 640
  },
  {
    "id": "frag_stair",
    "w": 640,
    "h": 476
  },
  {
    "id": "frag_wall",
    "w": 640,
    "h": 615
  },
  {
    "id": "frag_wedge",
    "w": 454,
    "h": 640
  }
];

export const TOP_FRAGMENTS: FragmentInfo[] = [
  {
    "id": "top_block",
    "w": 640,
    "h": 621
  },
  {
    "id": "top_louvre",
    "w": 640,
    "h": 216
  },
  {
    "id": "top_plaza",
    "w": 630,
    "h": 640
  },
  {
    "id": "top_roof_a",
    "w": 640,
    "h": 627
  },
  {
    "id": "top_roof_b",
    "w": 640,
    "h": 456
  }
];
