"""
Turn generated "collage fragment" pictures (flat white background) into transparent greyscale PNGs.

  python3 tools/fragments/build_fragments.py <source-dir>

Reads <source-dir>/frag_*.jpg (side fragments) and top_*.jpg (plan fragments), removes the white
background (every near-white region that touches the border or is large), crops to the bounding box,
downsizes to <= MAX_SIDE px and writes
  apps/web/public/fragments/<name>.png        (greyscale + alpha)
  apps/web/src/lib/parliament/fragments.data.ts   (names + pixel sizes; GENERATED)
Also writes apps/web/public/textures/concrete_board.jpg from concrete_tile_sample_*.jpg if present.

The pictures are AI-generated (see docs/free-assets-concrete-cigarettes.md for the licence discussion).
"""
import glob
import json
import os
import re
import sys

import numpy as np
from PIL import Image
from scipy import ndimage as ndi

MAX_SIDE = 640
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT_DIR = os.path.join(ROOT, "apps/web/public/fragments")
TEX_DIR = os.path.join(ROOT, "apps/web/public/textures")
DATA_TS = os.path.join(ROOT, "apps/web/src/lib/parliament/fragments.data.ts")


def cut(path):
    im = Image.open(path).convert("L")
    g = np.asarray(im).astype(np.float32)
    border = np.concatenate([g[0], g[-1], g[:, 0], g[:, -1]])
    bg = float(np.median(border))
    thr = max(222.0, min(bg - 12.0, 246.0))
    light = g > thr
    lab, n = ndi.label(light, structure=np.ones((3, 3)))
    sizes = ndi.sum(light, lab, index=np.arange(1, n + 1))
    touch = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]])).tolist()) - {0}
    big = {i + 1 for i, s in enumerate(sizes) if s > 0.004 * g.size}
    bgmask = np.isin(lab, list(touch | big))
    alpha = (~bgmask).astype(np.float32)
    alpha = ndi.binary_erosion(alpha > 0.5, iterations=1).astype(np.float32)
    alpha = ndi.gaussian_filter(alpha, 0.8)
    a8 = np.clip(alpha * 255, 0, 255).astype(np.uint8)
    out = Image.merge("LA", (im, Image.fromarray(a8)))
    ys, xs = np.where(a8 > 10)
    out = out.crop((xs.min(), ys.min(), xs.max() + 1, ys.max() + 1))
    s = MAX_SIDE / max(out.size)
    if s < 1:
        out = out.resize((round(out.size[0] * s), round(out.size[1] * s)), Image.LANCZOS)
    return out


def main(src):
    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(TEX_DIR, exist_ok=True)
    kinds = {"side": [], "top": []}
    for path in sorted(glob.glob(os.path.join(src, "*.jpg"))):
        base = os.path.basename(path)
        m = re.match(r"(frag|top)_(.+?)_\d{10,}\.jpg$", base)
        if not m:
            continue
        kind = "side" if m.group(1) == "frag" else "top"
        name = f"{m.group(1)}_{m.group(2)}"
        im = cut(path)
        im.save(os.path.join(OUT_DIR, name + ".png"), optimize=True)
        kinds[kind].append({"id": name, "w": im.size[0], "h": im.size[1]})
        print(kind, name, im.size, os.path.getsize(os.path.join(OUT_DIR, name + ".png")) // 1024, "KB")
    for path in glob.glob(os.path.join(src, "concrete_tile_sample_*.jpg")):
        t = Image.open(path).convert("L").resize((512, 512), Image.LANCZOS)
        t.save(os.path.join(TEX_DIR, "concrete_board.jpg"), quality=88)
        print("texture", t.size)
    with open(DATA_TS, "w") as f:
        f.write("// GENERATED by tools/fragments/build_fragments.py - do not edit.\n")
        f.write("export interface FragmentInfo {\n  id: string;\n  /** Pixel size of the cut-out PNG (aspect = w / h). */\n  w: number;\n  h: number;\n}\n\n")
        f.write("export const SIDE_FRAGMENTS: FragmentInfo[] = " + json.dumps(kinds["side"], indent=2) + ";\n\n")
        f.write("export const TOP_FRAGMENTS: FragmentInfo[] = " + json.dumps(kinds["top"], indent=2) + ";\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
